####################################################################################################
# Rollout Controller Build stage which performs the actual build of argo-rollouts binaries
####################################################################################################
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.22 AS argo-rollouts-build

# Set the working directory for the build
WORKDIR /go/src/github.com/argoproj/argo-rollouts

# Set the user to the default non-root user provided by UBI
USER root

# Copy only go.mod and go.sum files to optimize build caching
COPY argo-rollouts/go.mod argo-rollouts/go.sum ./
RUN go mod download

# Copy pre-built UI files for the plugin build
COPY argo-rollouts-ui-builds/59e5bd385c031600f86075beb9d77620f8d7915e/app argo-rollouts/ui/dist/app

# Copy the project files, including the .git directory
COPY . .

# Create required UI build markers to avoid rebuilds without Yarn installed
RUN cd argo-rollouts && \
    touch ui/dist/node_modules.marker && \
    mkdir -p ui/dist/app && \
    touch ui/dist/app/index.html && \
    find ui/dist

# Build the plugins for multiple platforms
RUN cd argo-rollouts && go mod vendor && make plugin-linux plugin-darwin plugin-windows

####################################################################################################
# Package the binaries into the image using UBI (Universal Base Image)
####################################################################################################
FROM registry.access.redhat.com/ubi8/ubi

# This directory is checked by the ecosystem-cert-preflight-checks task in Konflux
COPY LICENSE /licenses/

# Set the user to the default non-root user provided by UBI
USER 999

WORKDIR /

# Copy the built plugin binaries into the final image
COPY --from=argo-rollouts-build /go/src/github.com/argoproj/argo-rollouts/argo-rollouts/dist/kubectl-argo-rollouts-darwin-amd64 /releases
COPY --from=argo-rollouts-build /go/src/github.com/argoproj/argo-rollouts/argo-rollouts/dist/kubectl-argo-rollouts-darwin-arm64 /releases
COPY --from=argo-rollouts-build /go/src/github.com/argoproj/argo-rollouts/argo-rollouts/dist/kubectl-argo-rollouts-linux-amd64 /releases
COPY --from=argo-rollouts-build /go/src/github.com/argoproj/argo-rollouts/argo-rollouts/dist/kubectl-argo-rollouts-linux-arm64 /releases
COPY --from=argo-rollouts-build /go/src/github.com/argoproj/argo-rollouts/argo-rollouts/dist/kubectl-argo-rollouts-windows-amd64 /releases

# Add required labels
LABEL name="Argo Rollouts Kubectl plugin binaries" \
      summary="Argo Rollouts Kubectl plugin binaries" \
      description="Argo Rollouts Kubectl plugin binaries for various platforms, including Darwin and Linux."

# Define the entrypoint
# ENTRYPOINT ["<entrypoint-executable>"]
